- booquest-api/build.gradle
- booquest-api/src/main/java/com/booquest/booquest_api/config/SwaggerConfig.java
- 스웨거 사용을 위한 설정
- Resolved: #4 
- 추후 Security 사용시 설정 추가 필요
- jwt 사용시 설정 추가 필요
> [chore] 스웨거 설정 완료

- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/auth/web/DevAuthController.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/auth/JwtTokenProvider.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/auth/TokenUseCase.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/auth/JwtTokenPort.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/auth/dto/TokenInfo.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/service/auth/SocialLoginService.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/service/auth/TokenService.java
- booquest-api/src/main/java/com/booquest/booquest_api/config/SecurityConfig.java
- booquest-api/src/main/resources/application.yml
[Feature] 테스트용 토큰 발급 API 구현, 토큰 로직 리팩토링
- 개발용 컨트롤러 추가
- 테스트용 토큰 발급 API 구현
- 토큰 로직 리팩토링
- Resolved: #14 
- 
-
> [Feature] 테스트용 토큰 발급 API 구현, 토큰 로직 리팩토링

- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/onboarding/web/OnboardingController.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/onboarding/web/dto/OnboardingDataRequest.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/auth/persistence/UserQueryAdapter.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/auth/persistence/jpa/UserRepository.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/character/persistence/CharacterPersistenceAdapter.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/character/persistence/jpa/CharacterRepository.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/sidejob/AiSideJobGenerator.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/character/CreateCharacterUseCase.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/dto/GenerateSideJobRequest.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/dto/SubmitOnboardingData.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/onboarding/SubmitOnboardingUseCase.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/sidejob/GenerateSideJobUseCase.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/user/UpdateUserProfileUseCase.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/character/CharacterCommandPort.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/sidejob/GenerateSideJobPort.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/user/UserCommandPort.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/user/UserQueryPort.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/service/auth/SocialLoginService.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/service/character/CharacterService.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/service/onboarding/OnboardingService.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/service/sidejob/GenerateSideJobService.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/service/user/UserService.java
- booquest-api/src/main/java/com/booquest/booquest_api/config/SecurityConfig.java
- booquest-api/src/main/java/com/booquest/booquest_api/domain/character/enums/CharacterType.java
- booquest-api/src/main/java/com/booquest/booquest_api/domain/character/model/UserCharacter.java
- booquest-api/src/main/java/com/booquest/booquest_api/domain/user/model/User.java
- booquest-api/src/main/resources/db/migration/V4__add_user_profile_image_social_nickname.sql
- booquest-api/src/main/resources/db/migration/V5__add_character_character_type.sql
- booquest-api/src/test/java/com/booquest/booquest_api/application/service/onboarding/OnboardingServiceIntegrationTest.java
- booquest-api/src/test/java/com/booquest/booquest_api/application/service/onboarding/OnboardingServiceTest.java
- 온보딩 데이터 닉네임, 캐릭터 타입, 캐릭터 이름 입력
- 온보딩시 유저 닉네임수정, 캐릭터 생성
- 테스트 편의를 위한 1인 1온보딩 인증 로직 주석처리
- #6 
- 
-
> [Feat] wireframe V3 온보딩 반영

- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/onboarding/web/sidejob/SideJobController.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/onboarding/web/sidejob/dto/RegenerateAllSideJobRequest.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/onboarding/web/sidejob/dto/RegenerateRequest.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/onboarding/web/sidejob/dto/RegenerateSideJobRequest.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/sidejob/AiSideJobGenerator.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/sidejob/persistence/SideJobRepository.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/sidejob/persistence/SideJobRepositoryAdapter.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/sidejob/RegenerateSideJobUseCase.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/sidejob/SideJobGenerationResult.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/sidejob/GenerateSideJobPort.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/sidejob/SideJobRepositoryPort.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/service/sidejob/GenerateSideJobService.java
- booquest-api/src/main/java/com/booquest/booquest_api/common/exception/GlobalExceptionHandler.java
- booquest-api/src/test/java/com/booquest/booquest_api/application/service/sidejob/GenerateSideJobServiceTest.java
- 부업 전체 재생성
- 피드백 반영한 부업 개별 재생성 
- 
- Resolved: #23
- 
-
> [Feat] 부업 재생성 기능 구현

- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/sidejob/SideJobController.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/sidejob/dto/RegenerateAllSideJobRequest.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/sidejob/dto/RegenerateSideJobRequest.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/sidejob/AiSideJobGenerator.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/sidejob/persistence/SideJobRepository.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/sidejob/persistence/SideJobRepositoryAdapter.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/sidejob/RegenerateSideJobUseCase.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/sidejob/SelectSideJobUseCase.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/sidejob/GenerateSideJobPort.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/sidejob/SideJobRepositoryPort.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/service/sidejob/GenerateSideJobService.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/service/sidejob/SelectSideJobService.java
- booquest-api/src/main/java/com/booquest/booquest_api/config/SecurityConfig.java
- booquest-api/src/test/java/com/booquest/booquest_api/application/service/sidejob/GenerateSideJobServiceTest.java
- 유저가 추천받은 부업들 전체 조회 기능 구현
- controller sidejob 패키지 위치 변경
- 
- 
-
> [Feat] 유저가 추천받은 부업들 조회 기능 구현

- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/missionstep/MissionStepController.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/missionstep/dto/MissionStepUpdateStatusRequest.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/missionstep/dto/MissionStepUpdateStatusResponse.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/mission/persisitence/MissionRepository.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/missionstep/persisitence/MissionStepRepositoryAdapter.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/missionstep/UpdateMissionStepStatusUseCase.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/missionstep/MissionStepRepositoryPort.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/service/missionstep/UpdateMissionStepStatusService.java
- booquest-api/src/main/java/com/booquest/booquest_api/domain/character/model/UserCharacter.java
- booquest-api/src/main/java/com/booquest/booquest_api/domain/missionstep/model/MissionStep.java
- booquest-api/src/main/resources/application.yml
부 퀘스트 상태 업데이트 (완료/완료취소 포함) API 구현
- 부 퀘스트 상태 업데이트 (완료/완료취소 포함) API 구현
- 메인 퀘스트 목록 정렬 수정
- Swagger UI 알파벳순으로 정렬
- Resolved: #25 
- 
-
> [Feature] 부 퀘스트 상태 업데이트 (완료/완료취소 포함) API 구현

- booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/onboarding/CheckSideJobStatusUseCase.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/service/sidejob/CheckSideJobStatusService.java
> fix : long -> Long 수정

- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/character/web/dto/CharacterGrowthResponse.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/character/persistence/CharacterRewardRepositoryAdapter.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/character/UpdateCharacterExpUseCase.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/character/CharacterRewardPort.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/service/character/CharacterRewardService.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/service/character/CharacterService.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/service/missionstep/UpdateMissionStepStatusService.java
- booquest-api/src/main/java/com/booquest/booquest_api/domain/character/enums/RewardType.java
- booquest-api/src/main/java/com/booquest/booquest_api/domain/character/model/UserCharacter.java
- booquest-api/src/main/java/com/booquest/booquest_api/domain/character/policy/CharacterRewardPolicy.java
- booquest-api/src/main/java/com/booquest/booquest_api/domain/character/policy/FixedLevelingPolicy.java
- booquest-api/src/main/java/com/booquest/booquest_api/domain/character/policy/FixedPerCompletionPolicy.java
- booquest-api/src/main/java/com/booquest/booquest_api/domain/character/policy/LevelingPolicy.java
캐릭터 성장률 조회 API 수정
- 
- 
- 
- 
-
> 캐릭터 성장률 조회 API 수정

- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/usersidejob/UserSideJobController.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/usersidejob/dto/UserSideJobSummaryResponse.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/income/persistence/IncomeRepository.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/income/persistence/IncomeRepositoryAdapter.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/missionstep/persisitence/MissionStepRepository.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/missionstep/persisitence/MissionStepRepositoryAdapter.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/income/IncomeRepositoryPort.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/missionstep/MissionStepRepositoryPort.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/service/usersidejob/GetUserSideJobSummaryService.java
부업 요약 조회 API 구현
- 부업 요약 조회 API 구현
- 
- 
- 
-
> [Feature] 부업 요약 조회 API 구현

- booquest-api/src/main/java/com/booquest/booquest_api/application/service/character/CharacterService.java
캐릭터 디폴트 설정(임시)
- 디폴트 이름 Boo, avatarUrl null
- 
- 
- 
-
> [Fix] 캐릭터 디폴트 설정(임시)

- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/user/UserController.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/service/character/CharacterService.java
> [Fix] 캐릭터 디폴트 이름 설정 [Feature] 엔드포인트 변경

- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/income/web/dto/IncomeResponse.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/service/income/GetIncomeListService.java
수익 목록 조회 - 누적 금액 추가
- 수익 목록 조회 - 누적 금액 추가
- 
- 
- 
-
> [Feature] 수익 목록 조회 - 누적 금액 추가

- booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/missionstep/persisitence/MissionStepRepository.java
> [fix] : missionId -> mission.id 수정

- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/auth/web/AuthController.java
- booquest-api/src/main/java/com/booquest/booquest_api/config/SecurityConfig.java
SecurityConfig - auth 및 logout 관련 수정
- /api/auth/** 전체 허용으로 단순화
- logout/all 비활성화
- 
- 
-
> [Refactor] SecurityConfig - auth 및 logout 관련 수정

- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/missionstep/dto/MissionStepUpdateStatusResponse.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/service/mission/CompleteMissionService.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/service/missionstep/UpdateMissionStepStatusService.java
- 메인퀘스트 완료 시 경험치 계산 오류 수정
- 부퀘스트 완료/완료취소 시 불필요한 응답값 제거
- 
- 
-
> [Fix] 경험치 계산 오류 수정 및 불필요한 응답값 제거

- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/mission/MissionController.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/mission/dto/MissionCompleteResponse.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/service/mission/CompleteMissionService.java
- booquest-api/src/main/java/com/booquest/booquest_api/domain/mission/enums/MissionCompleteStatus.java
메인퀘스트 완료 응답값 status 추가
- 메인퀘스트 완료 응답값 status 추가
- 
- 
- 
-
> [Feature] 메인퀘스트 완료 응답값 status 추가

- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/sidejob/dto/RegenerateSideJobRequest.java
> [refactor] 부업 재생성 피드백 enum 수정

- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/auth/web/AuthController.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/auth/oauth/NaverOAuthClient.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/auth/oauth/dto/NaverUserResponse.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/service/auth/SocialLoginService.java
- booquest-api/src/main/resources/application.yml
- booquest-api/src/test/java/com/booquest/booquest_api/auth/application/service/SocialLoginServiceTest.java
네이버 로그인 API 구현
- 네이버 로그인 API 구현
- 
- 
- 
-
> [Feature] 네이버 로그인 API 구현

- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/auth/web/DevAuthController.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/mission/MissionController.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/mission/dto/MissionResponseDto.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/missionstep/MissionStepController.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/auth/JwtTokenProvider.java
- booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/mission/persisitence/MissionRepositoryAdapter.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/auth/TokenUseCase.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/mission/SelectMissionUseCase.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/missionstep/SelectMissionStepUseCase.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/sidejob/UpdateSideJobUseCase.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/auth/JwtTokenPort.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/mission/MissionRepositoryPort.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/service/auth/TokenService.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/service/mission/SelectMissionService.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/service/missionstep/SelectMissionStepService.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/service/sidejob/UpdateSideJobService.java
- booquest-api/src/main/java/com/booquest/booquest_api/domain/sidejob/model/SideJob.java
- 메인퀘스트 / 부퀘스트 생성시 데이터가 존재하면 해당 데이터 응답
- 테스트 토큰 발급 api userId 입력하도록 수정
- 
- Resolved: #74 
- 
-
> [Feat] 메인퀘스트 / 부퀘스트 생성시 데이터가 존재하면 해당 데이터 응답

- booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/chat/web/ChatController.java
- booquest-api/src/main/java/com/booquest/booquest_api/application/service/chat/ChatService.java
챗봇 대화 제목 생성 기능 구현
- 챗봇 대화 제목 생성 기능 구현
- 
- 
- 대화의 첫 메시지를 짧게 요약하여 제목을 생성합니다.
-
> [Feature] 챗봇 대화 제목 생성 기능 구현
